apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oq2b0iswh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oq2b0iswh-nodejs 
  name: oq2b0iswh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oq2b0iswh-nodejs 
